### ISSUE TITLE
Migrate site to https

### ISSUE THREAD

**Issue by edwardchalstrey1** [MajidBenam/seshat#3]
Currently the Seshat website uses http: http://seshat-db.com/ which registers as insecure in the browser. It may be worth getting an SSL certificate, both for security purposes and so that users are not concerned when visiting the website.

On Chrome for me, the website is viewable by default, but perhaps currently on other browsers you might need to click "I trust this site" or similar?

**Comment by MajidBenam** [comment]
I totally get what you're saying, and it's been on my mind as well. I actually gave it a shot to snag a free SSL Certificate from AWS for seshat-db.com, but it didn't work out because we got the domain from another provider. If you've had any experience setting up an SSL certificate for a website on AWS EC2 with Nginx, I'd love to hear about it. Otherwise, I'll definitely give it another shot as soon as I can carve out some time.

**Comment by edwardchalstrey1** [comment]
Nice, it's not something I've done before and I don't think it's urgent but more of a nice-to-have (same for #4 ). I could definitely consider looking into these kinds of things a bit later on, but imagine I will have my hands full with database stuff for the time being. I think it's worth having a wish-list of improvements even if no-one has time to work on them any time soon, so may add other things as I think of them 😃

**Comment by MajidBenam** [comment]
Totally agree. I might find some time this month and give both tasks another go. and we can keep all such issues here for us to not forget them. Awesome.

**Comment by MajidBenam** [comment]
I have taken care of this.
